name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Refresh tags and categories for the Solodit
      id: refreshRequest
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: https://solodit.xyz/api/general/refresh_tag_category/
        method: POST
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: '{"email": "${{ secrets.SOLODIT_USER }}", "password": "${{ secrets.SOLODIT_PASSWORD }}"}'
    - name: Show Response of Refreshing Tags and Categories
      run: |
        echo ${{ steps.refreshRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
    - name: Import reports
      id: importReportRequest
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: https://solodit.xyz/api/general/import_reports/
        method: POST
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: '{"email": "${{ secrets.SOLODIT_USER }}", "password": "${{ secrets.SOLODIT_PASSWORD }}"}'
    - name: Show Response of Importing Reports
      run: |
        echo ${{ steps.importReportRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
